### ISSUE TITLE
Backend package missing parameters

### ISSUE THREAD

**Issue by Ehesp** [clerkinc/javascript#1023]
## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [x] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Dependencies + versions

Provide a json with the dependencies used in your project (copy paste from yarn.lock / package-lock.json) or a github project / template that reproduces the issue.

**Include the @clerk/* packages and their versions!**

Example:

```json
"@clerk/clerk-sdk-node": "^4.8.1",
"@clerk/remix": "^2.5.0",
```

## Description

The [Backend API docs](https://clerk.com/docs/reference/backend-api/tag/Organizations#operation/ListOrganizations) have quite a lot of parameters, for example "Get a list of organizations for an instance":

![image](https://user-images.githubusercontent.com/842078/229536168-05513bd6-dc0f-4aad-b262-123e6e17f3bd.png)

However, if you use the Client Backend node package, only a few of these parameters are available:

```ts
client.organizations.getOrganizationList(...);
```

On this API, only `limit` and `offset` are available:

```ts
type GetOrganizationListParams = {
    limit?: number;
    offset?: number;
};
```

The same is true for updating an organisation, `slug` is in the docs but not in the types.

**Comment by Ehesp** [comment]
I can still set the params and they do work - just using `@ts-expect-error` for now

**Comment by dimkl** [comment]
Hello @Ehesp :) . Thank you for reporting this issue. Since you have made all that work (the investigation) and found the root cause, would you be interested in opening a PR to resolve this issue? Otherwise i will try to open a PR by the end of the day.

**Comment by dimkl** [comment]
Also @Ehesp why do you import `"@clerk/clerk-sdk-node": "^4.8.1",` package ?

**Comment by Ehesp** [comment]
@dimkl I can do this (and was going to), however before doing that is there any open spec which these types could potentially be generated with? Seems like this is going to be reoccurring problem if it's manual?

Happy to do this anyway.

> Also @Ehesp why do you import "@clerk/clerk-sdk-node": "^4.8.1", package ?

Ah ignore this, it was my bad.
