### ISSUE TITLE
Module Not Found error: 'fs' when updated to 4.15.0 with next.js 13.3

### ISSUE THREAD

**Issue by jonnguyen12** [clerkinc/javascript#1046]
## Package + Version

- [x ] `@clerk/nextjs` version: 4.15.0

I updated clerk package to 4.15 today and next.js to 13.3 as well.
Then I have this error:

```
./node_modules/.pnpm/next@13.3.0_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/@vercel/og/index.node.js:17950:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.3.0_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/.pnpm/next@13.3.0_@babel+core@7.21.4_react-dom@18.2.0_react@18.2.0/node_modules/next/server.js
./node_modules/.pnpm/@clerk+nextjs@4.15.0_next@13.3.0_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/nextjs/dist/app-beta/auth.js
./node_modules/.pnpm/@clerk+nextjs@4.15.0_next@13.3.0_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/nextjs/dist/app-beta/index.js
./node_modules/.pnpm/@clerk+nextjs@4.15.0_next@13.3.0_react-dom@18.2.0_react@18.2.0/node_modules/@clerk/nextjs/app-beta/index.js
./app/dashboard/layout.tsx
```

My usage for clerk is inside SimpleNavBar (client component),
I imported 
`import {UserButton} from "@clerk/nextjs/app-beta"`

I also tried to add the clerk package to the list of serverComponentsExternalPackages in next.config.js like this:
`serverComponentsExternalPackages: [ "@clerk/nextjs"],` and it is still not working. Maybe I should use @clerk/nextjs inside Server Components only?

Thanks

**Comment by jonnguyen12** [comment]
I figured it out. It was the import. 
Closed this issue.

**Comment by jonnguyen12** [comment]
> What did you do to fix it? I am getting a similar issue right now:
> 
> ```
> Module not found: Can't resolve 'fs'
> 
> https://nextjs.org/docs/messages/module-not-found
> 
> Import trace for requested module:
> ./node_modules/next/dist/server/web/spec-extension/image-response.js
> ./node_modules/next/server.js
> ./node_modules/@clerk/nextjs/dist/app-beta/auth.js
> ./node_modules/@clerk/nextjs/dist/app-beta/index.js
> ./node_modules/@clerk/nextjs/app-beta/index.js
> ./src/app/layout.tsx```
> ```

I changed my import to this
`import {UserButton} from "@clerk/nextjs"`

**Comment by claritise** [comment]
Currently on `"@clerk/nextjs": "^4.16.3"` and `"next": "^13.2.4"` and still getting the error when I that. I am using the `import { ClerkProvider } from "@clerk/nextjs/app-beta";` module for the `app` directory. Just attempting to wrap that context would give me this error.

**Comment by jonnguyen12** [comment]
I would recommend when you're on the latest version of Clerk for the app directory. You should always keep your Next version latest as well. Mine is 13.3.0. 
Once you upgraded them all, I would recommend reset packages like this:

- remove the following folders: node_modules, .next, npm or pnpm lock file. 
- reinstall the packages
- if you are using PNPM, i would do an extra step: pn store prune and pn prune.

Hope that helps.

**Comment by claritise** [comment]
Unfortunately the newest version of next isn't playing well with some of my other dependencies. Ill try seeing if any of them have updated since i've last tried getting it to 13.3. Appreciate the help.
