### ISSUE TITLE
signInUrl/signUpUrl and Internationalized Routing

### ISSUE THREAD

**Issue by harrisrobin** [clerkinc/javascript#1058]
- [x] Review the documentation: https://clerk.com/docs
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Dependencies + versions

```json
{  
  "dependencies": {
    "@clerk/localizations": "^1.10.0",
    "@clerk/nextjs": "^4.14.2",
    "@clerk/themes": "^1.5.1",
    "@clerk/types": "^3.34.0",
    "@emotion/react": "^11.10.6",
    "@prisma/client": "^4.10.1",
    "@radix-ui/colors": "^0.1.8",
    "@radix-ui/react-aspect-ratio": "^1.0.2",
    "@radix-ui/react-avatar": "^1.0.2",
    "@radix-ui/react-dropdown-menu": "^2.0.4",
    "@radix-ui/react-separator": "^1.0.2",
    "@stitches/react": "^1.2.8",
    "@tanstack/react-query": "^4.28.0",
    "@trpc/client": "^10.19.1",
    "@trpc/next": "^10.19.1",
    "@trpc/react-query": "^10.19.1",
    "@trpc/server": "^10.19.1",
    "clsx": "^1.1.1",
    "formik": "^2.2.9",
    "jotai": "^2.0.3",
    "jotai-devtools": "^0.4.0",
    "jotai-form": "^0.1.0",
    "lucide-react": "^0.130.1",
    "next": "^13.2.1",
    "next-themes": "^0.2.1",
    "plaiceholder": "^2.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "sharp": "^0.32.0",
    "superjson": "^1.7.4",
    "typesafe-i18n": "^5.24.3",
    "zod": "^3.0.0",
    "zod-formik-adapter": "^1.2.0"
  },
  "devDependencies": {
    "@playwright/test": "^1.26.1",
    "@swc-jotai/react-refresh": "^0.0.7",
    "@types/node": "^18.7.20",
    "@types/react": "^18.0.9",
    "@typescript-eslint/eslint-plugin": "^5.47.0",
    "@typescript-eslint/parser": "^5.47.0",
    "eslint": "^8.30.0",
    "eslint-config-next": "^13.2.1",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-webpack": "^0.13.2",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-react": "^7.31.11",
    "eslint-plugin-react-hooks": "^4.6.0",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.7.1",
    "prisma": "^4.10.1",
    "start-server-and-test": "^1.12.0",
    "tsx": "^3.12.3",
    "typescript": "^4.8.3",
    "vite": "^4.1.2",
    "vitest": "^0.29.8"
  },
}

```

## Description

I am using nextjs with automatic locale detection, and when you have that on it appends your locale to the URL.

For example, it will append: 
`/no-NO` to the URL. 

I noticed that when i use the Clerk SignUp component it doesn't handle this locale properly It ends up appending it twice for some reason. 

See this:

https://user-images.githubusercontent.com/3880008/230762258-0270735f-38f3-47c0-b75f-15d215782260.mp4

My SignIn component basically looks like this:

```
      <SignIn path={clerkPath} routing="path" signUpUrl="/sign-up" />
```

Is there a way for me to handle where it goes to entirely in my app rather than pass it a route? Is there a workaround or something I should be doing?

Thank you,

**Comment by RehmanAmjad** [comment]
I'm facing a similar internationalized routing issue on Next JS. When I load the page `/sign-in/`, everything loads but when I use `/en/sign-in/` then it doesn't load.

I have my folders stored as `pages/sign-in/[[...index]].tsx`.

**Comment by harrisrobin** [comment]
just wanted to add: we're not launched yet but this is a pretty big problem for us as our app needs to be translated. I would hate to have to write my own UI components just because of this.

**Comment by rwieruch** [comment]
How I fixed it for me.

```
import { useRouter } from 'next/router';
import React from 'react';
import { SignIn } from '@clerk/nextjs';
import { Page } from '~/components/page';

const SignInPage = () => {
	const router = useRouter();

	const once = React.useRef(false);
	React.useEffect(() => {
		if (once.current) return;
		once.current = true;

		if (router.locale === 'de') return;
		router.replace(router.asPath, router.asPath, { locale: 'de' });
	});

	return (
		<Page
			style={{
				justifyContent: 'center',
				alignItems: 'center',
			}}
		>
			<SignIn
				path="/sign-in"
				routing="path"
				signUpUrl="/sign-up"
				redirectUrl="/"
			/>
		</Page>
	);
};

export default SignInPage;
```

**Comment by nikosdouvlis** [comment]
Hello @harrisrobin and @theramjad , we're currently investigating - we'll get back to you as soon as possible.

**Comment by desiprisg** [comment]
Hello. We've identified the issue. The fix will be available in the next release. @theramjad, you need to include the `router.locale` in the paths that are passed to the `<SignIn />` component. That should do the trick.
Example: 
```
import { SignIn } from "@clerk/nextjs";
import { useRouter } from "next/router";

const SignInPage = () => {
  const router = useRouter();
  return <SignIn path={`/${router.locale}/sign-in`} routing="path" signUpUrl={`/${router.locale}/sign-up`} />;
};

export default SignInPage;
```

**Comment by nikosdouvlis** [comment]
We've identified the issue - a fix will be deployed with our next release.

**Comment by theramjad** [comment]
Thank you @desiprisg for the trick.

Unfortunately, there is a little bug with the ```signUpUrl={`/${router.locale}/sign-up`}```. When I click on the link, it takes me to `/en/sign-up` as expected but then I get automatically redirected to `/en/en/sign-up` after which the page does not appear.

Any idea what is happening? I'm unsure whether this is a Next.js problem or a Clerk problem.

My code is,
```
import { SignUp } from "@clerk/nextjs";
import { useRouter } from "next/router";
import { Card, Container } from "react-bootstrap";

export default function Page({ allow_sign_up }) {
  const router = useRouter();
  let locale;

  // In path and signUpUrl, you have to use locale as a path parameter
  if (router.locale === process.env.NEXT_PUBLIC_DEFAULT_LOCALE) {
    locale = "";
  } else {
    locale = "/" + router.locale;
  }

  return (
    <div className="align-items-center d-flex justify-content-center min-vh-100">
      <SignUp
        path={`${locale}/sign-up`}
        routing="path"
        signInUrl={`${locale}/sign-in`}
        appearance={{
          layout: {
            socialButtonsPlacement: "bottom",
          },
        }}
      />
    </div>
  );
}
```

**Comment by desiprisg** [comment]
@theramjad This sounds like the original issue of this thread. It should be fixed in the upcoming release. Let us know if you experience any more problems after that!

**Comment by porkytheblack** [comment]
experiencing a similar issue when I have the signin form in a nested path e.g ``/auth/signin/[[..index]].tsx`` and a similar setup for signup.

**Comment by theramjad** [comment]
> @theramjad This sounds like the original issue of this thread. It should be fixed in the upcoming release. Let us know if you experience any more problems after that!

Thank you. Is there a timeline for the next release?
