### ISSUE TITLE
German translation for formFieldLabel__emailAddresses is not consistent with other occurences of email addresses

### ISSUE THREAD

**Issue by matukosan** [clerkinc/javascript#1116]
## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [x] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `@clerk/chrome-extension`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

## Description
On the org member management dialog it says "E-mailadressen" instead of "E-Mail-Adressen", like on all other places email addresses are mentioned.

<img width="328" alt="CleanShot 2023-04-28 at 11 22 30@2x" src="https://user-images.githubusercontent.com/2116286/235110297-e557cbc7-6260-4781-ab2e-7357abe24620.png">

**Comment by matukosan** [comment]
created a PR here: https://github.com/clerkinc/javascript/pull/1117

**Comment by dimkl** [comment]
Closing this issue as it will be available in the next release.
