### ISSUE TITLE
Clerk get broken when clearing cookies manually.

### ISSUE THREAD

**Issue by bacharSalleh** [clerkinc/javascript#1211]
- [x] `@clerk/nextjs`

### Dependencies + versions

Provide a json with the dependencies used in your project (copy paste from yarn.lock / package-lock.json) or a github project / template that reproduces the issue.

**Include the @clerk/* packages and their versions!**

Example:

```json
{  
  "dependencies": {
    "next": "13.4.3",
     "@clerk/nextjs": "^4.18.2",
  },

}

```

## Description

I have followed the docs to setup Clerk. 

// middleware.ts
```
import { authMiddleware } from "@clerk/nextjs";

export default authMiddleware();

export const config = {
    matcher: ["/((?!.*\\..*|_next).*)", "/", "/(api|trpc)(.*)"],
};
```
// layout.tsx
```
export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body
                    className= "min-h-screen bg-background font-sans antialiased"
                >
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
```

- when running the app on locahost it redirects me to login. which is correct. but
when I clear the cookies by my self (open inspector and remove all cookies and clean local storage), Clerk starts to behave like it is broken. unlimited redirect from my localhost to clerk and vice versa.

and I'm getting this error message in my console 
```
🔒 Clerk:
The <SignUp/> and <SignIn/> components cannot render when a user is already signed in, unless the application allows multiple sessions. Since a user is signed in and this application only allows a single session, Clerk is redirecting to the Home URL instead.
(This notice only appears in development)

```

**Comment by anagstef** [comment]
Hello @bacharSalleh! Thank you for opening this issue. This is indeed a bug that will be solved when #1241 is merged to production!
