### ISSUE TITLE
OrganizationSwitcher missing root appearance attribute

### ISSUE THREAD

**Issue by raffi1300** [clerkinc/javascript#1504]
- [2.8.1] `@clerk/remix`
Dependencies:

```json
  "dependencies": {
    "@clerk/remix": "^2.8.1",
    "react": "^18.2.0",
  }
```

I'm using the Organization Switcher component and trying to style it's root layout (ie to make it full-width and not  "fit-content", which is the default style applied in the "cl-internal-xxx" class.

 It is not available as an appearance attribute. Following the styling guide, "organizationSwitcher" is not available or variations including root.

ie: cl-rootBox cl-organizationSwitcher-root 🔒️ cl-internal-xxxxx
targeting rootBox causes other design elements to fail.

I reviewed the repo and there is no missing element that my intellisense is not picking up, or there is a class name I am not realizing would target this element.

**Comment by panteliselef** [comment]
Hey @raffi1300 thanks for reaching out.

What i tried and seems to work is the following
```jsx
<OrganizationSwitcher
    appearance={{
      elements: {
        rootBox: {
          width: "100%",
        },
      },
    }}
/>
```

or if you want to provide a class (f.e tailwind)
```jsx
<OrganizationSwitcher
    appearance={{
      elements: {
        rootBox: {
            rootBox: "w-full",
        },
      },
    }}
/>
```

**Comment by jescalan** [comment]
@raffi1300 - does this resolve your issue?

**Comment by raffi1300** [comment]
It does! Thanks for checking. I was originally setting the style globally on the context, but setting it on the component itself makes it work correctly. Thanks for the insight @panteliselef !
