### ISSUE TITLE
csrf/xss related

### ISSUE THREAD

**Issue by terlan4** [clerkinc/javascript#1549]
Hi, can somebody explain this paragraph from docs in more details please? 
`navigation alone should never trigger a mutation in your backend` ??

And my second question is if I use Clerk both in next.js frontend and in express or Go backend, I dont need to care about csrf at all?

>### Do I need to take additional steps to prevent CSRF attacks?
>You do not, but it is still possible to accidentally make your application vulnerable to XSS attacks.
>
>Because Clerk uses the Lax setting, it is critical to remember that navigation alone should never trigger a mutation in your backend. Otherwise, the user can be tricked into clicking a link that takes an action they did not intend.

**Comment by jescalan** [comment]
Hey @terlan4 - questions like this would be great to ask in [Clerk's community server](https://discord.gg/tghyUaCurJ), rather than posted as issues on github 🙏
