### ISSUE TITLE
ClerkProvider typescript error

### ISSUE THREAD

**Issue by usman-coe** [clerkinc/javascript#209]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [ ] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
3.2.8
```

## Description
ClerkProvider typescript error, **I use this package on monorepo sytem by Turborepo**
`
'ClerkProvider' cannot be used as a JSX component.
  Its element type 'ReactElement<any, any> | Component<ClerkProviderProps, any, any> | null' is not a valid JSX element.
    Type 'Component<ClerkProviderProps, any, any>' is not assignable to type 'Element | ElementClass | null'.
      Type 'Component<ClerkProviderProps, any, any>' is not assignable to type 'ElementClass'.
        The types returned by 'render()' are incompatible between these types.
          Type 'React.ReactNode' is not assignable to type 'import("/home/usman/repo/workdii_mono/node_modules/@types/react-transition-group/node_modules/@types/react/index").ReactNode'.
            Type '{}' is not assignable to type 'ReactNode'
`
![image](https://user-images.githubusercontent.com/2543952/165134980-c90a343b-2f3a-41b3-833e-3c295b21b5db.png)
![image](https://user-images.githubusercontent.com/2543952/165135019-5e06bd3a-92cc-4234-aff7-bba222bd94e1.png)

**Comment by nikosdouvlis** [comment]
Hello @usman-coe , thanks for the report.

Could you please run `npm ls --depth=1 | grep -E 'clerk|react'` in your project's root and share the output?

**Comment by nikosdouvlis** [comment]
Hello again, we've just released another round of React 18 fixes. Please try installing the latest `@clerk/clerk-react` version by running `npm i @clerk/clerk-react@latest` and let me know if you hit any other issues.

**Comment by nikosdouvlis** [comment]
Hello again, we've just released another round of React 18 fixes. Please try installing the latest `@clerk/clerk-react` version by running `npm i @clerk/clerk-react@latest` and let me know if you hit any other issues.

Feel free to reopen this issue if you need any help.

**Comment by usman-coe** [comment]
Hello, @nikosdouvlis  Sorry for late reply.
This error is gone when I use the latest version.  Thanks for fix it.
