### ISSUE TITLE
Session already exists error doesn't get forwarded so we can't handle it

### ISSUE THREAD

**Issue by hammy2899** [clerkinc/javascript#230]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs` 3.6.1
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
3.6.1
```

### Browser/OS

If applicable e.g. `Chrome latest`

## Description

When trying to register a user while a session already exists the error thrown simply says "Error:"

To find out that the session already existed I had to view the request response in dev tools to see the payload error.

Simple fix is to just forward that error on so we can check for it.

![image](https://user-images.githubusercontent.com/11588822/167889981-8c5cbedd-41d5-41a0-84d5-267f989fb082.png)
![image](https://user-images.githubusercontent.com/11588822/167890070-51225053-c6de-4e81-93a2-099bf9193fc8.png)

**Comment by SokratisVidros** [comment]
Hi @hammy2899. Thanks for reporting this. 

Can you please share a code snippet that reproduces the issue using the `useSignIn` hook?

**Comment by hammy2899** [comment]
@SokratisVidros the blank error gets thrown on callback when using the `<AuthenticateWithRedirectCallback />` component

So simply this page will cause the error
```jsx
export const SSOCallback: NextPage = () => {
  return <AuthenticateWithRedirectCallback />
}
```

**Comment by SokratisVidros** [comment]
Thanks @hammy2899. We are already working on a fix.

**Comment by dimkl** [comment]
https://github.com/clerkinc/javascript/pull/790
