### ISSUE TITLE
Error JSON not parsing correctly

### ISSUE THREAD

**Issue by rfdrake27** [clerkinc/javascript#289]
- [ ] Review the documentation: https://docs.clerk.dev/
- [ ] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [ ] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

 
- [ ] `@clerk/clerk-sdk-node`
 

### Version:

 3.6.16

### Browser/OS

Edge 102.0

## Description

When using the `createUser` method, if there is an error, it returns `error SyntaxError: Unexpected token o in JSON at position 1`, instead of the actual error. It appears the issue is likely originating from @clerk/backend-core/dist/cjs/api/utils/ErrorHandler.js, from the JSON.parse method.

**Comment by mpowell90** [comment]
I'm seeing this error with  `"@clerk/clerk-sdk-node": "^3.6.2"`

**Comment by SokratisVidros** [comment]
Hi @mpowell90. Thanks, for bringing this to our attention. The error indicates that the Clerk Backend response wasn't a valid JSON. This can happen if an unexpected 502 timeout error occurs due to a network hiccup. Does the error persist?

**Comment by igneel64** [comment]
@mpowell90 
Thanks for reporting, we will be deploying the fix as soon as possible :)

**Comment by igneel64** [comment]
@mpowell90 
Our latest version `3.8.2` includes the fix :)
