### ISSUE TITLE
Property 'env' is missing in type is missing in Next API Request with auth prop

### ISSUE THREAD

**Issue by calebfaruki** [clerkinc/javascript#316]
## Package + Version

- `@clerk/nextjs@3.8.1`
- `@clerk/types@2.20.0`
- `@clerk/clerk-sdk-node@3.9.0`

## Description

```
Argument of type '(req: WithAuthProp<NextApiRequest>, res: NextApiResponse) => void' is not assignable to parameter of type 'Middleware'.
  Types of parameters 'req' and 'req' are incompatible.
    Type 'WithAuthProp<Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>>' is not assignable to type 'WithAuthProp<NextApiRequest>'.
      Property 'env' is missing in type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>> & { auth: { sessionId: string | null; userId: string | null; getToken: ServerGetToken; claims: ClerkJWTClaims | null; }; }' but required in type 'NextApiRequest'.ts(2345)
```

Here is the code:

```
// pages/api/get-authenticated-user.ts
import { withAuth, WithAuthProp } from '@clerk/nextjs/api';
import type { NextApiRequest, NextApiResponse } from 'next';

export default withAuth(
  (req: WithAuthProp<NextApiRequest>, res: NextApiResponse) => {
    const { sessionId } = req.auth;

    if (!sessionId) {
      return res.status(401).json({ id: null });
    }

    return res.status(200).json({ id: sessionId });
  }
);
```

**Comment by SokratisVidros** [comment]
Hi there. Thanks for reporting. Which version of nextjs are you using?

**Comment by erhise** [comment]
Can confirm this one => using `@clerk/nextjs@3.8.1` `next@12.2.3`

**Comment by drasch** [comment]
I'm running next 12.1.6

I too am running into this issue with Typescript. `withAuth` is now looking for a function with `express` `Request` and `Response` instead of `NextApiRequest` and `NextApiResponse`


This is what I had to change as a workaround for typescript. 


```
+import type { Request, Response } from 'express' 


-  async (req: WithAuthProp<NextApiRequest>, res: NextApiResponse) => {                      
+  async (req: WithAuthProp<Request>, res: Response) => {                                    
```

Unfortunately for some other libraries I had to use `req as any as NextApiRequest` because the types were incorrect.

**Comment by Renetnielsen** [comment]
+1 for this issue

**Comment by Renetnielsen** [comment]
@calebfaruki @drasch @erhise 
I temp fixed this by manually adding `@clerk/clerk-sdk-node@3.9.0` and changing my import to use that.
As far as i could see the `@clerk/nextjs/api` uses a different version of the `3.3.10`

```
+ import { RequireAuthProp, requireAuth } from '@clerk/clerk-sdk-node';
- import { RequireAuthProp, requireAuth } from '@clerk/nextjs/api';
```

**Comment by Renetnielsen** [comment]
I temporarily fixed this by doing the following:

```
- import { RequireAuthProp, requireAuth } from '@clerk/nextjs';
+ import { RequireAuthProp, requireAuth } from '@clerk/clerk-sdk-node';
```

And adding fixed version of the SDK (Even though its normally not needed).
`"@clerk/clerk-sdk-node": "3.8.1",`

**Comment by SokratisVidros** [comment]
Folks, we've started working on a fix. It requires some internal typing restructuring and you should expect a fix by the end of this week.
