### ISSUE TITLE
Casing in NPM @clerk/backend-core is broken, breaking the package on Linux

### ISSUE THREAD

**Issue by no2chem** [clerkinc/javascript#324]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [N/A] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-expo`
- [x] `@clerk/backend-core`
- [x] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
1.14.1
```

## Description

It would appear that backend-core contains an incorrectly cased import. This completely breaks anything that depends on it on any case-sensitive file system.

When using clerk-sdk-node on Linux, for example, the error:

```
Error: Cannot find module './ClerkBackendApi'
```

Is returned. Digging into this further, it seems that the file is named "ClerkBackendAPI.js" in the npm tarball:

```
tar xvzf backend-core-1.14.1.tgz
...
x package/dist/cjs/api/ClerkBackendAPI.js
x package/dist/mjs/api/ClerkBackendAPI.js
x package/dist/cjs/api/ClerkBackendAPI.d.ts
x package/dist/mjs/api/ClerkBackendAPI.d.ts
...

```
Now, macos and Windows have default case insensitive filesystems, so the package works fine, which makes this a real surprise when your application suddenly stops working after moving it into a Docker container.

Running the build locally, it seems all the files are properly named:

```
npm notice 1.7kB   dist/cjs/api/ClerkBackendApi.d.ts                                
npm notice 1.5kB   dist/cjs/api/ClerkBackendApi.d.ts.map                            
npm notice 4.6kB   dist/cjs/api/ClerkBackendApi.js  
```

So I'm not quite sure how they got renamed like that in the NPM tarball.

**Comment by no2chem** [comment]
For anyone who runs into this issue, I've used gitpkg to create a package you can install that fixes the casing issue:

```
npm install 'https://gitpkg.now.sh/clerkinc/javascript/packages/backend-core?8fec9785cc3424c51144a3164675aaa86f30a5c9&scripts.postinstall=tsc%20-p%20tsconfig.esm.json%20--skipLibCheck%20%26%26%20tsc%20-p%20tsconfig.cjs.json%20--skipLibCheck%20%26%26%20.%2FmoduleTypeFix'
```

But, now I run into Error: Cannot find module './Crypto' in @clerk/clerk-sdk-node/dist/utils/index.js which I suspect is another casing issue...

**Comment by igneel64** [comment]
Thanks for bringing this to our attention @no2chem . We are looking into it and we are gonna be shipping a fix in the next few hours.

**Comment by no2chem** [comment]
Yeah, wow - I'm not sure what's going on with the filenames ... Crypto.ts is renamed crypto.js in your tarballs. 

Honestly, I'm a bit surprised no one else has run into this issue? Surely the current NPM packages would break for anyone running on a case-sensitive filesystem.

```
npm install 'https://gitpkg.now.sh/clerkinc/javascript/packages/sdk-node?8fec9785cc3424c51144a3164675aaa86f30a5c9&scripts.postinstall=node%20.%2Fscripts%2Finfo.js%20%26%26%20tsc%20-p%20tsconfig.build.json%20--skipLibCheck%20%26%26%20tsc%20-p%20tsconfig.esm.json%20--skipLibCheck'
```

Will fix the issue with './Crypto' in @clerk/clerk-sdk-node

**Comment by igneel64** [comment]
@no2chem We just released a new version which should fix the casing issue in both `clerk-sdk-node` and `backend-core` 
If you spot anything unusual let us know :)

**Comment by no2chem** [comment]
@igneel64  - the tarballs look good to me now, thanks! Curious --- what was the reason for the rename? I can't tell from the commits

**Comment by SokratisVidros** [comment]
This should be now fixed. Shall we close it?

**Comment by no2chem** [comment]
Yeah it can be closed. Thanks!
