### ISSUE TITLE
yarn peerDependencies issue

### ISSUE THREAD

**Issue by Himself65** [clerkinc/javascript#337]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [x] `@clerk/edge`
- [ ] other:

### Version:

```
node 18.7.0
yarn 3.2.2
```

### Browser/OS

On development side

## Description

```shell
✗ yarn
➤ YN0000: ┌ Resolution step
➤ YN0002: │ @clerk/edge@npm:1.7.5 doesn't provide react (pda14f), requested by next
➤ YN0002: │ @clerk/edge@npm:1.7.5 doesn't provide react-dom (pe2ef3), requested by next
➤ YN0002: │ @clerk/nextjs@npm:4.0.2 [1a981] doesn't provide react (p632b5), requested by @clerk/clerk-react
```

**Comment by SokratisVidros** [comment]
@Himself65 can you please provide more information about the issue and paste your package.json? Have you installed react and react-dom packages to your project?

**Comment by Himself65** [comment]
> @Himself65 can you please provide more information about the issue and share your package.json? Have you installed react and react-dom packages to your project?

I think the solution is your package to add react and react-dom to peer dependency

**Comment by SokratisVidros** [comment]
That's weird. @clerk/edge doesn't import `react` or `react-dom`. Moreover, both packages are [peer dependencies](https://www.runpkg.com/?next@12.2.5/package.json#80) for the `next` package.

**Comment by nikosdouvlis** [comment]
Closing this one for now as we haven't been able to reproduce this one locally. Please feel free to reopen in the future if you need more assistance.
