### ISSUE TITLE
UserProfile "hideNavigation" and "only" not working

### ISSUE THREAD

**Issue by slowbaker** [clerkinc/javascript#355]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
4.1.3
```

## Description

No matter what values are used for `UserProfile.hideNavigation` or `UserProfile.only`, the entire user profile component is being rendered. `UserProfile.appearance` seems to work fine.

```jsx
import { UserProfile } from '@clerk/nextjs';

export default function AccountSettings() {
  return (
    <UserProfile
      appearance={{
        variables: {
          colorPrimary: '#f00',
        },
      }}
      hideNavigation
      only="security"
    />
  );
}
```
<img width="957" alt="Screenshot 2022-08-31 at 18 18 46" src="https://user-images.githubusercontent.com/39057579/187729871-e59c8cec-50ef-40bc-895c-200ef9642179.png">

**Comment by nikosdouvlis** [comment]
Hello @slowbaker , many thanks for the report.

These options were v3 specific so they shouldn't work with the new v4 components. Looks like these 2 types were not updated accordingly - I'll be fixing this as soon as possible.

However, can you please provide more info about your actual use case? I'd like to discuss with the team above the possibility of re-introducing these for the v4 components as well :)

**Comment by slowbaker** [comment]
Thanks for the fast response. In my opinion, at least `hideNavigation` should be supported so that we can remove the sidebar. 

Currently, if the main content area is short (almost always the case), nothing happens when you click on one of the navigation links. That's a UX issue.

**Comment by nikosdouvlis** [comment]
> Thanks for the fast response. In my opinion, at least `hideNavigation` should be supported so that we can remove the sidebar.
> 
> Currently, if the main content area is short (almost always the case), nothing happens when you click on one of the navigation links. That's a UX issue.

My understanding is that you're using the mounted version of the UserProfile, not the default modal so that makes a lot of sense. I will forward this thread to the team so we can discuss further and I'll report back here when I have more details.

For now, do you think hiding the navbar using the `appearance` api would be an acceptable workaround? Eg: 
```
<UserProfile
  appearance={{
    elements: {
      navbar: { display: 'none' },
    },
  }}
/>
```
