### ISSUE TITLE
Incorrect type for getUserOauthAccessToken

### ISSUE THREAD

**Issue by jasonkuhrt** [clerkinc/javascript#527]
- [ ] Review the documentation: https://docs.clerk.dev/
- [ ] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [ ] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
4.5.7
```

### Browser/OS

If applicable e.g. `Chrome latest`

## Description

Describe your issue in detail, a demo repository or a sandbox would be great.

This is an incorrect type:

```
    getUserOauthAccessToken(userId: string, provider: `oauth_${string}`): Promise<User>;
```

It actually returns not a `User` but something like (taken from runtime log):

```ts
[
    {
      object: 'oauth_access_token',
      token: 'ghu_REDACTED',
      provider: 'oauth_github',
      public_metadata: {},
      label: null,
      scopes: [Array]
    }
  ]
```

**Comment by emmiep** [comment]
I have already submitted an issue regarding this: #447

**Comment by jasonkuhrt** [comment]
Thanks @emmiep
