### ISSUE TITLE
`WithClerkState.data` prop should be optional

### ISSUE THREAD

**Issue by dvargas92495** [clerkinc/javascript#54]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.
    - `clerk.rjzug.yeali.lcl.dev`

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [x] `@clerk/clerk-remix`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
0.1.0-alpha.0
```

### Browser/OS

`Chrome latest`

## Description

Currently the type, `WithClerkState`, associated with being used with `useLoaderData` has a type that implies that the `data` prop is guaranteed: https://github.com/clerkinc/javascript/blob/next/packages/remix/src/ssr/types.ts#L5-L8.

However, when trying out the package with my project, `data` was undefined bc an `interstitial` was returned from `getAuthData` in `rootAuthLoader`: https://github.com/clerkinc/javascript/blob/next/packages/remix/src/ssr/rootAuthLoader.ts#L28-L30

So, this leads me to the following questions/suggestions, in order of preference:
1. What is interstitial? Ideally, `getAuthData` would return the user either logged in or out and then I would have my data returned.
2. If interstitial is kept, could we return `data` so that I always have access to it?
3. If I cannot keep data, then it should be optional on `WithClerkState`

**Comment by nikosdouvlis** [comment]
Hello there, many thanks for the great feedback. 

About the interstitial - when a JWT is expired (among other edge cases), we use an interstitial to refresh the JWT and then reload the page. The interstitial is thrown by middleware in our SDKs that intercepts requests **before** the developer's application does any processing.

Currently, Remix doesn't provide a way for us to handle the interstitial from within a Remix loader without requiring the user to manually update `entry.server.ts` or `entry.client.ts` and `root.tsx`.  Given these limitations and the fact that we consider the interstitial an implementation detail, we've just opened a PR that properly hides the interstitial state while keeping setup to a minimum.

Happy to help if you need any assistance 

More details can be found here : #66

**Comment by colinclerk** [comment]
Merged in #66
