### ISSUE TITLE
Remix experimental cloudflare pages

### ISSUE THREAD

**Issue by tobiasfoerg** [clerkinc/javascript#579]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [x] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
1.4.0-staging.4
```

### Browser/OS

If applicable e.g. `Chrome latest`

## Description

I want to get the `User` object within a loader. 
So i used `import {clerk} from "@clerk/remix/experimental/api.server"`.

I receive following error:
```
Error: Missing Clerk API Key. Go to https://dashboard.clerk.dev and get your Clerk API Key for your instance.
...
```
I think it is related to follwing file.
https://github.com/clerkinc/javascript/blob/f6ef89d301f72efa3d1b1151162d6d17629c64f9/packages/remix/src/experimental/clerk.ts#L5

it works in the `rootAuthLoader` because there the variable is read from the `context` object.

Am i missing something?

**Comment by SokratisVidros** [comment]
@tobiasfoerg I'd suggest to wait for an official release tomorrow as this comes from a staging tag that we are still testing. Did you set CLERK_API_KEY in your app?

**Comment by tobiasfoerg** [comment]
Yea i do. It is inside the context object.

As I mentioned the way the apiKey is received is different then in the rootAuthLoader.

**Comment by SokratisVidros** [comment]
You are right. We need to fix this tomorrow.

**Comment by SokratisVidros** [comment]
@tobiasfoerg Which runtime are you using for this? Is it CF pages?
