### ISSUE TITLE
Remix 1.8 seems to break ClerkApp or ClerkCatchBoundary

### ISSUE THREAD

**Issue by gsong** [clerkinc/javascript#594]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard: `clerk.correct.lacewing-23.lcl.dev`

## Package + Version

- [x] `@clerk/remix`: 1.4.1

## Description

We have three Remix apps that use the same Clerk app for authentication. All three apps are hosted on the same domain:

- app1.domain
- app2.domain
- app3.domain

We've been developing and deploying just fine until we upgraded to the latest Remix 1.8.1, which has routing changes and changes to how throw responses are handled by CatchBoundary, which is why I suspect the issue is either in ClerkApp or ClerkCatchBoundary.

Right now we just get a 401 and then nothing. The interstitial never loads (which is what's responsible for loading `clerk_browser.js` if I'm understanding things correctly).

Instead of `data.clerkState.__internal_clerk_state`, I get a message `🔒 Clerk: This state shouldn't be possible. Please reach out to support@clerk.dev so we can help...`

<https://github.com/remix-run/remix/releases/tag/remix%401.8.0>

**Comment by SokratisVidros** [comment]
@gsong Thanks for reporting this. We are aware of this issue and we are already working on a fix.

**Comment by gsong** [comment]
> Please follow this issue for more updates: [remix-run/remix#4791](https://github.com/remix-run/remix/issues/4791)

@nikosdouvlis Thank you for the thorough investigation on this, really impressed.

**Comment by nikosdouvlis** [comment]
@gsong Thank you! :)

This is going to be fixed by https://github.com/remix-run/react-router/pull/9702 in an upcoming Remix release - possibly the next one.

However, just letting you know that we've released `@clerk/remix@1.4.2` which includes a hotfix that should unblock you until the official Remix fix is out. Feel free to try it out and please let me know if you hit any issues.

**Comment by gsong** [comment]
@nikosdouvlis I can confirm that the hot fix worked for our use case.
