### ISSUE TITLE
Clerk API key not found during initialization of Express Middleware

### ISSUE THREAD

**Issue by carolinmaisenbacher** [clerkinc/javascript#623]
## Package + Version

```
@clerk/clerk-sdk-node@4.5.13
```

## Description

I am trying to setup an Apollo GraphQL server, which uses express as the base layer, and the Clerk Express Middleware `ClerkExpressWithAuth`. 

However, when following the documentation I get the following error: 

```
file:///sandbox/node_modules/@clerk/clerk-sdk-node/dist/chunk-LF24WFXO.mjs:131
      throw Error(SupportMessages.API_KEY_NOT_FOUND);
            ^

Error:
Clerk API key not found during initialization.
Please visit https://github.com/clerkinc/clerk-sdk-node#options--env-vars-available for more information.
```
I added the `CLERK_API_KEY` in the .env.local file at the root of the directory, but it does not load it.

### Codesandbox

Here is a codesandbox that experiences the same issue: https://codesandbox.io/s/apollo-server-clerk-62f4ie?file=/index.js

I set dummy values for the .env.local variables - but I am getting the same error when adding the correct api keys in my local repository, so I don' think it has any effects on my issue.

(The graphql interface would be accessible when navigating to the `/api` route. However at the moment the server is crashing, because of the error described above.)

### Possible solution: 
Allow to set the CLERK_API_KEY manually when initiating the middleware. 
The general `Clerk` class already allows this (https://clerk.dev/docs/reference/node/getting-started#custom-instantiation).

**Comment by nikosdouvlis** [comment]
Closing this one as the latest `@clerk/clerk-sdk-node` release should've solved the original issue, as @dimkl said above. Please feel free to reopen if you need any more help!
