### ISSUE TITLE
Provide <ClerkProvider> with existing Clerk client

### ISSUE THREAD

**Issue by hornta** [clerkinc/javascript#626]
## Package

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] `@clerk/localizations`
- [ ] other:

## Description

It would be nice to be able to provide the `<ClerkProvider>` component in `@clerk/clerk-react` with an already existing Clerk client so that I only have one active Clerk client on my website. Right now I have to pass a frontend api key and it spins up its own client which is a small problem because it executes extra requests for the client created in react.

![image](https://user-images.githubusercontent.com/4553604/209017709-7fbb6ca7-a1d8-4d45-b714-117bc04083be.png)

```ts
// clerk.ts
import Clerk from "@clerk/clerk-js";

export const frontendApi = import.meta.env.VITE_CLERK_FRONTEND_API;
export const clerk = new Clerk(frontendApi);
clerk.load();
```

```ts
// App.tsx
import {
  ClerkProvider,
  RedirectToSignIn,
  SignedIn,
  SignedOut,
} from "@clerk/clerk-react";
import { ProtectedApp } from "./ProtectedApp.js";
import { frontendApi } from "./clerk.js";

export const App = () => {
  return (
    <ClerkProvider frontendApi={frontendApi}>
      <SignedIn>
        <ProtectedApp />
      </SignedIn>
      <SignedOut>
        <RedirectToSignIn />
      </SignedOut>
    </ClerkProvider>
  );
};
```

I want this

```ts
import { clerk} from "./clerk.js";

...

<ClerkProvider client={clerk}>
```

**Comment by SokratisVidros** [comment]
@hornta This is already support via the `Clerk` prop. You can do the following:

```js
import { clerk } from "./clerk.js";

<ClerkProvider Clerk={clerk} />
```

**Comment by hornta** [comment]
Thanks
