### ISSUE TITLE
Invalid state error after changing username

### ISSUE THREAD

**Issue by visortelle** [clerkinc/javascript#634]
## Package + Version

- [x] `@clerk/clerk-react`

### Version:

```
4.7.0
```

### Browser/OS

If applicable e.g. `Chrome latest`

## Description

- I created a Clerk application.
- Signed in as a new user.
- Enabled the checkbox to allow users to change their usernames.
- Now I encounter an error when I'm trying to change my username. Sometimes (maybe once in 10 times) it randomly works as expected.

https://user-images.githubusercontent.com/9302460/209434814-248265e5-e5f7-4626-90f4-8e6882492a3e.mov

After the page reload, the username has been changed.

For newly created users, setting a username always works correctly.

**Comment by desiprisg** [comment]
I am unable to reproduce this. Can you provide a repo/sandbox where this happens?

**Comment by visortelle** [comment]
@desiprisg sorry, but I don't have free time to create the sandbox now. 

If you can't reproduce it, let's close it, until anyone else will report the same issue.

**Comment by desiprisg** [comment]
Hi again. It has come to my attention that this issue must have been fixed in a later version, `4.7.2` to be exact.
