### ISSUE TITLE
Minor visual issue - phone code area overflow

### ISSUE THREAD

**Issue by visortelle** [clerkinc/javascript#635]
## Package + Version

- [x] `@clerk/clerk-react`

### Version:

```
4.7.0
```

### Browser/OS

If applicable e.g. `Chrome latest`

## Description

<img width="706" alt="Screenshot 2022-12-24 at 9 05 25 PM" src="https://user-images.githubusercontent.com/9302460/209449751-4cd1eb2e-b893-4c7d-a5c3-3708adc48430.png">

If remove the `min-height` property for `. cl-selectButton`, it looks OK.

<img width="725" alt="Screenshot 2022-12-24 at 9 02 59 PM" src="https://user-images.githubusercontent.com/9302460/209449703-2924d5b9-fd9a-4f82-bfa1-bf8e204c3f71.png">

**Comment by desiprisg** [comment]
I am unable to reproduce this. Can you provide a repo/sandbox?

**Comment by visortelle** [comment]
@desiprisg sorry, but I don't have free time to create the sandbox now. 

If you can't reproduce it, let's close it, until anyone else will report the same issue.
