### ISSUE TITLE
Missing named export `withAuth` making the prisma-fastify starter not work

### ISSUE THREAD

**Issue by hornta** [clerkinc/javascript#697]
This https://github.com/clerkinc/clerk-fastify-react-prisma-starter doesn't work with latest version(4.6.2) of the clerk node sdk because `withAuth` is not exported.

**Comment by nikosdouvlis** [comment]
Hello @hornta , thanks for the report. We're working on it (and we will also make any required changes to support fastify). I'll post an update here and on discord as soon as possible.

**Comment by dimkl** [comment]
Hello @hornta , we have updated the  https://github.com/clerkinc/clerk-fastify-react-prisma-starter and we have introduced a `@clerk/fastify` plugin to support Fastify.
Could you check the updated starter project ?
Also you can find examples of clerk/fastify [here](https://github.com/clerkinc/clerk-fastify-starter)

**Comment by nikosdouvlis** [comment]
Closing this one as the changes are already live - please feel free to reopen if you need more assistance.
