### ISSUE TITLE
externalId is missing in type definitions of getUserList

### ISSUE THREAD

**Issue by IGassmann** [clerkinc/javascript#739]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard: `clerk.learnarena.com`

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/clerk-sdk-node`
- [x] `@clerk/backend`
- [ ] other:

### Version:

```
2.12.1
```

### Browser/OS

Chrome latest

## Description

The backend API [supports the `external_id` query parameter](https://clerk.dev/docs/reference/backend-api/tag/Users#operation/GetUserList!in=query&path=external_id&t=request) on the `GET /v1/users` endpoint, but it is missing [on the type definition of the SDK](https://github.com/clerkinc/javascript/blob/0d13cebce146a23db6cde495a8a06fe90a7b9c98/packages/backend/src/api/endpoints/UserApi.ts#L9).

**Comment by dimkl** [comment]
@IGassmann Thanks for reporting this. We have updated the type definitions in the SDK and it should be available in our next release.
