### ISSUE TITLE
SSR state with buildClerkProps

### ISSUE THREAD

**Issue by mvcodelabs** [clerkinc/javascript#793]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
4.10.0
```

### Browser/OS

MacOS + Chrome (all latest)

## Description

in `getServerSideProps` passing the preloaded user + organization throws 
```
error - TypeError: Cannot read properties of undefined (reading 'find')
at ClerkContextProvider (/Users/redacted/workspace/project/node_modules/@clerk/clerk-react/dist/contexts/ClerkContextProvider.js:33:84)
```
if I preload only user OR organization it works fine. preloaded session is not a problem

The offending line is 
```js
const organizationMembership = organization
        ? user === null || user === void 0 ? void 0 : user.organizationMemberships.find(m => m.organization.id === organizationId)
        : organization;
```

After carefully reading the source code i suppose it all starts from [here](https://github.com/clerkinc/javascript/blob/560c9dfd992ceb32f7c02202dff40fc666dc546c/packages/react/src/contexts/ClerkContextProvider.tsx#L137)
```
// github: clerkinc/packages/javascript/react/src/contexts/ClerkContextProvider.tsx
const user = initialState.user as any as UserResource;
```

**Comment by nikosdouvlis** [comment]
Hello @mvcodelabs , thanks for the report - let me investigate and get back to you as soon as possible.

**Comment by nikosdouvlis** [comment]
We've identified the issue. It'll be fixed with our next release - I'll also update the thread here when the fix is out :)
