### ISSUE TITLE
orgId unavailable in SSR

### ISSUE THREAD

**Issue by mvcodelabs** [clerkinc/javascript#797]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
4.10.0
```

### Browser/OS

Macos + Chrome (latest)

## Description

```js
const { userId, orgId } = useAuth()
//      ^ ".."  ^ null  
```

after passing `...buildClerkProps(req)`in `getServerSideProps` the `orgId` is not available, even if the user is already logged in as an org.

The ssr context is the following

```
{
   "props":{
      "pageProps":{
         "__clerk_ssr_state":{
            "sessionClaims":{
               "azp":"http://localhost:3000",
               "exp":1676306531,
               "iat":1676306471,
               "iss":"https://above-gelding-56.clerk.accounts.dev",
               "jti":"8e210fb4384b8c7f42fa",
               "nbf":1676306461,
               "org_id":"org_2LYs9dB0jm10lCqsoJVewF5gQbC",
               "org_role":"admin",
               "org_slug":"demo",
               "sid":"sess_2Lf25B8Zv7AAQ3yA0FVW9xOJrze",
               "sub":"user_2L0OLR4hWMIPcuQn5KMh5d9ryRK",
               "user":{
                  "email":"mattia@mvcodelabs.it",
                  "id":"user_2L0OLR4hWMIPcuQn5KMh5d9ryRK",
                  "image":"https://www.gravatar.com/avatar?d=mp",
                  "name":{
                     "first":"Mattia",
                     "full":"{{user.first_name}} {{user.last_name}}",
                     "last":"Vitturi"
                  },
                  "org":{
                     "id":"org_2LYs9dB0jm10lCqsoJVewF5gQbC",
                     "name":"Ristorante Demo",
                     "role":"admin",
                     "slug":"demo"
                  },
                  "phone":null
               }
            },
            "sessionId":"sess_2Lf25B8Zv7AAQ3yA0FVW9xOJrze",
            "userId":"user_2L0OLR4hWMIPcuQn5KMh5d9ryRK",
            "orgId":"org_2LYs9dB0jm10lCqsoJVewF5gQbC",
            "orgRole":"admin",
            "orgSlug":"demo"
         }
      },
      "__N_SSP":true
   },
   "page":"/settings",
   "query":{
      
   },
   "buildId":"development",
   "isFallback":false,
   "gssp":true,
   "scriptLoader":[
      
   ]
}
```

as you can the the `orgId` is populated but unavailable in `getAuth()` on the server

**Comment by dimkl** [comment]
Hello @mvcodelabs , thanks for the report. I will check it and come back to you :)

**Comment by dimkl** [comment]
@mvcodelabs Could you provide a repo with the issue?

**Comment by nikosdouvlis** [comment]
Update: no need to provide a repo; we've identified this issue as well - a fix will be shipped with our next release early tomorrow.
