### ISSUE TITLE
Better DX

### ISSUE THREAD

**Issue by heymartinadams** [clerkinc/javascript#798]
Would it be possible for you to not only [tag](https://github.com/clerkinc/javascript/tags) but also [release](https://github.com/clerkinc/javascript/releases) each new version update?

I get a notification each time a new version has been published, which is quite important to keep the code current. If a `tag` isn’t made into a `release`, there won’t be a notification.

<img width="509" alt="CleanShot 2023-02-13 at 09 34 41@2x" src="https://user-images.githubusercontent.com/11673745/218530839-04e1455b-d237-4cfc-a7b9-473bf02f5703.png">

Also, it’d be nice to see what updates were made. [NextJS](https://github.com/vercel/next.js/releases) does a great job.

<img width="1155" alt="CleanShot 2023-02-13 at 09 38 52@2x" src="https://user-images.githubusercontent.com/11673745/218531703-1d0086d1-730f-4cee-a3f1-73ba512f8ef0.png">

Hopefully you can integrate it into your development process.

**Comment by nikosdouvlis** [comment]
Hello @heymartinadams, 
This is on our radar already, and we do have plans for improvements in our release process - you can expect them within the next few weeks. I'll update this issue when the changes are live :)

Would you like to add anything else to this thread or should I close this one?

**Comment by heymartinadams** [comment]
Thanks so much @nikosdouvlis 💯  Nothing else, appreciate it.
