### ISSUE TITLE
Include sessionClaims when injecting auth into request. 

### ISSUE THREAD

**Issue by nicksrandall** [clerkinc/javascript#826]
Specifically, I'd like access to`sessionClaims.orgs`

## Package

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [x] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

## Description

Is there a reason why we don't include the session claims by default and only include the actor? 
See: https://github.com/clerkinc/javascript/blob/main/packages/remix/src/ssr/utils.ts#L20

**Comment by nicksrandall** [comment]
I'm happy to include a PR if you're open to adding this.

**Comment by SokratisVidros** [comment]
This is an omission on our end. It's there in [Next.js](https://github.com/clerkinc/javascript/blob/aaf68d90e2769abc18f3fb6e8011066a7a2068c6/packages/nextjs/src/middleware/utils/injectAuthIntoRequest.ts#L15). 

If you want you can open a PR or we will fix it in our next cycle.
