### ISSUE TITLE
Remix - strange SSR issue with getAuth

### ISSUE THREAD

**Issue by Scott-Fischer** [clerkinc/javascript#850]
- [X] Review the documentation: https://docs.clerk.dev/
- [X] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [X] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [X] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
2.2.4
```

### Browser/OS

Node v16, Node v18

## Description

I'm continuously seeing an `API key error` when attempting to call getAuth in a loader with a specified JWT template. Removing the `template` argument restores proper functionality and works just fine but anytime I specify a valid JWT template name, I see the following error:
<img width="980" alt="image" src="https://user-images.githubusercontent.com/8835133/220460354-8b0628da-aba4-417a-95b7-f1546e84a11c.png">

### To sum it up
This throws:
```ts
import { getAuth } from "@clerk/remix/ssr.server";

export const loader: LoaderFunction = async (args) => {
  const { userId, getToken } = await getAuth(args);
  const token = await getToken({template: 'supabase'});
  // do whatever with token
  return { serialisedUser: JSON.stringify(user) };
}
```

This works:
```ts
import { getAuth } from "@clerk/remix/ssr.server";

export const loader: LoaderFunction = async (args) => {
  const { userId, getToken } = await getAuth(args);
  const token = await getToken();
  // do whatever with token
  return { serialisedUser: JSON.stringify(user) };
}
```

This can be reproduced easily with the [remix-auth-starter](https://github.com/clerkinc/remix-auth-starter) repo by destructuring getToken from getAuth and supplying any string value to template in this [loader function](https://github.com/clerkinc/remix-auth-starter/blob/main/app/routes/ssr-user-demo.tsx#L9)

**Comment by dimkl** [comment]
Hello @Scott-Fischer thank you for reporting the issue. Let me take a look and come back to you.

**Comment by dimkl** [comment]
Fixed is deployed in the latest release!
