### ISSUE TITLE
clerk-expo @0.12.5 not working with expo-router

### ISSUE THREAD

**Issue by sgrund14** [clerkinc/javascript#870]
- [ ] Review the documentation: https://docs.clerk.dev/
- [ ] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [ ] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [x] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
clerk-expo @ 0.12.5
expo @ 48.0.4
expo-router @ 1.0.0-rc8
```

### Browser/OS

iOS Simulator

## Description

I'm getting an error with a basic `ClerkProvider` from clerk-expo in a new Expo project

```
/app/_layout.tsx

import { ClerkProvider } from '@clerk/clerk-expo';
import { Slot } from 'expo-router';
import * as SecureStore from 'expo-secure-store';

const CLERK_PUBLISHABLE_KEY =
    'pk_test';

export async function saveToken(key: string, value: string) {
    await SecureStore.setItemAsync(key, value);
}

export async function getToken(key: string) {
    const value = await SecureStore.getItemAsync(key);
    return value;
}

export default function App() {
    return (
        <ClerkProvider
            publishableKey={CLERK_PUBLISHABLE_KEY}
            tokenCache={{ getToken, saveToken }}
        >
            <Slot />
        </ClerkProvider>
    );
}

```

throws this mysterious error: `ReferenceError: Property 'EventTarget' doesn't exist`

to reproduce
1) clone into this repo https://github.com/chen-rn/CUA,  install dependencies, and replace public key at `/packages/app/provider/auth/index`
2) run `yarn native` and the iOS simulator will load your app
3) upgrade from v0.10.16 to v0.12.5
4) app breaks with `ReferenceError: Can't find variable: EventTarget `

full error looks like this: 
```
ReferenceError: Can't find variable: EventTarget 
RootRouteNodeProvider@http://{local-IP}:19000/index.ts.bundle?platform=ios&dev=true&hot=false:110944:23
ContextNavigator@http:///{local-IP}/index.ts.bundle?platform=ios&dev=true&hot=false:115292:24
RNCSafeAreaProvider
SafeAreaProvider@http:///{local-IP}/index.ts.bundle?platform=ios&dev=true&hot=false:103684:24
ExpoRoot@http:///{local-IP}/index.ts.bundle?platform=ios&dev=true&hot=false:115279:24
App
```

I have a hunch this has something to do with expo-router... can somebody help please :) ?

**Comment by Motoxpro** [comment]
Same error here, `ReferenceError: Can't find variable: EventTarget` Trying to just get basic setup going without the cache.

**Comment by SokratisVidros** [comment]
Thanks for reporting. We are already working on fix. 

Meanwhile, you can use `@clerk/clerk-expo@0.12.4` or try adding the following shim

https://www.npmjs.com/package/event-target-shim

```
import { EventTarget, Event } from "event-target-shim";
global.EventTarget = EventTarget
```

**Comment by sgrund14** [comment]
this still only works with this shim 🤔 

```
import { Event, EventTarget } from 'event-target-shim';

if (!global.EventTarget) {
    global.EventTarget = EventTarget;
}

if (!global.Event) {
    global.Event = Event;
}
```

**Comment by SokratisVidros** [comment]
The polyfill is incomplete, so I removed it from the original comment. The team will be back tomorrow, and we will ship the correct fix.
