### ISSUE TITLE
Clerk Expo errors/not working on all platforms and versions.

### ISSUE THREAD

**Issue by Motoxpro** [clerkinc/javascript#873]
- [ ] Review the documentation: https://docs.clerk.dev/
- [ ] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [ ] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ X ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
0.12.5
```

### Browser/OS

All

## Description

```
App.js (1247:889)
Can't find variable: EventTarget
(Device)
  Evaluating module://@clerk/clerk-expo.js
  Evaluating module://App.js.js
```
This error happens on all platforms, on my local computer, with all package versions, etc. Not sure I am doing something wrong but I have attached an extremely basic sandbox.

https://snack.expo.dev/@sagaapp/783e43

The `clerk-expo-starter repo` has the same problem. I've gone through all the `clerk-expo` versions back to .0.8.

Also tried what was suggested here

```
We have reproduced it locally and are working on a fix.

⚠️ Meanwhile, you can try using @clerk/clerk-expo@0.12.4 which is the latest working version. ⚠️

The problematic 0.12.5 version has been unpublished.
```

Update:
It seems like it only happens on the first load. So if I comment out all entry points to anything Clerk at the root of my app, reload it (`r`) and then uncomment and let it fast refresh, everything works as it should.

**Comment by Motoxpro** [comment]
The `clerk-expo-starter` repo has the same problem. I've gone through all the `clerk-expo` versions back to .0.8.

**Comment by Motoxpro** [comment]
Also tried what was suggested here

```
We have reproduced it locally and are working on a fix.

⚠️ Meanwhile, you can try using @clerk/clerk-expo@0.12.4 which is the latest working version. ⚠️

The problematic 0.12.5 version has been unpublished.
```

**Comment by SokratisVidros** [comment]
@Motoxpro This must be due to an Expo cached build. Version 0.12.4 should work as expected. I am gonna close this and the updates about the fix will be posted on https://github.com/clerkinc/javascript/issues/870.

**Comment by Motoxpro** [comment]
Thanks. Were you able to get it to work in the snack? I have tried it on multiple computers, snacks, etc. and I wasn't able to get 0.12.4 working either.

**Comment by SokratisVidros** [comment]
I used https://github.com/clerkinc/clerk-expo-starter in a local IOS simulator.

**Comment by Motoxpro** [comment]
@SokratisVidros I'm sorry to be a bother, but could you check the snack? Only added 2 lines of code from the basic starter. This is the smallest reproducible sample I can make (literally just adding ClerkProvider).

**Comment by sgrund14** [comment]
@SokratisVidros I'm getting 0.12.4 working, but only with the shim you suggested on the other issue 

```
import { Event, EventTarget } from 'event-target-shim';

if (!global.EventTarget) {
    global.EventTarget = EventTarget;
}

if (!global.Event) {
    global.Event = Event;
}
```

it doesn't work otherwise

**Comment by SokratisVidros** [comment]
The Snack is broken for me with a react-native error.

<img width="331" alt="Screenshot 2023-02-27 at 5 01 24 PM" src="https://user-images.githubusercontent.com/1352422/221598948-bc6990a6-0591-40df-bce7-9b8fa38fd7af.png">

The above polyfill doesn't work. That's why I removed it from the comment.

**Comment by sgrund14** [comment]
hmm. I get the `EventTarget` error without it, but it the error clears and the project builds with it

**Comment by SokratisVidros** [comment]
Can you please clone https://github.com/clerkinc/clerk-expo-starter locally and try again?

**Comment by SokratisVidros** [comment]
Can you run `npm why @clerk/clerk-expo` in the repo? What's the output?

**Comment by SokratisVidros** [comment]
Thanks, this is helpful. I see what's happening. Can you please try adding `"@clerk/clerk-js: "4.27.2"` to your package.json, remove the polyfill and try again?

**Comment by sgrund14** [comment]
ok, tried adding this and the EventTarget error is back :(

**Comment by SokratisVidros** [comment]
That's why the error is back. The error occurs in ClerkJS 4.28.X. You can use [yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) to ping @clerk/clerk-js to 4.27.2 version.

**Comment by sgrund14** [comment]
aha, ok! added a resolution to `"@clerk/clerk-js": "4.27.2"` in my root package.json and the error is gone without the polyfill 😄 thanks much

**Comment by SokratisVidros** [comment]
Glad it's working now and apologies for the hassle. We will ship the proper fix ASAP.
