### ISSUE TITLE
Allow `buildClerkProps` in `getServerSideProps` to return a not-authenticated state

### ISSUE THREAD

**Issue by roguealexander** [clerkinc/javascript#889]
## Package

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

## Description

When using Clerk in `getServerSideProps` like so

```
export const getServerSideProps = async ({ req }: any) => {
  const { userId } = getAuth(req);
  const user = userId ? await clerkClient.users.getUser(userId) : undefined;

  return {
    props: {
      ...buildClerkProps(req, { user }),
    },
  };
};
```
if the user is authenticated and userId is not null, the wrappers and functions like `useAuth()` and `<SignedIn>...</SignedIn>` (etc) will initialize with the correct auth state (as expected).

However, if the user isn't authenticated, `buildClerkProps` will return an empty object. Which causes `useAuth()` and others to default to a loading state on first render. This will resolve to `false` (as determined in `getServerSideProps`), which causes `<SignedOut>...</SignedOut>` to pop in.

Request: Allow `buildClerkProps` to either create a "not-authenticated" state in `__clerk_ssr_state` by default, or put it behind a flag.

I'm getting around this currently by not using `SignedOut` wrapper, but wrapping in a `{ !userId && <></>}` conditional, but the fix would allow more uniformity in the Clerk SSR experience.

Let me know what you think.

**Comment by nikosdouvlis** [comment]
Hello @roguealexander - this has been resolved. The fix will be deployed with our next release tomorrow.
Many thanks for the report :)
