### ISSUE TITLE
Question: Would we want to stop a regular user from being able to create a new organization?

### ISSUE THREAD

**Issue by magnusrodseth** [clerkinc/javascript#895]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Go through package changelog files. 

I saw that you recently made organizations a top-level functionality. Great! I'm building a web application where an administrator with access to the Clerk dashboard can create organizations and appoint a user as an admin of that organization. That organization administrator can then invite other users to join the organization, but the organization admin cannot create a new organization (only manage the one they have been appointed admin of).

The current `<OrganizationSwitcher />` component allows any user to create a new organization.

<img width="433" alt="Screenshot 2023-03-04 at 10 56 51" src="https://user-images.githubusercontent.com/59113973/222893557-66ea8c7d-b4bb-42b7-8d84-89f47308a00a.png">

I was wondering if it would be desirable to add a prop to the `<OrganizationSwitcher />` like this:

```tsx
<OrganizationSwitcher canCreateOrganization={false} />
```

The `canCreateOrganization` prop would default to true, and the developer would be able to override it. What are your thoughts on this?

**Comment by SokratisVidros** [comment]
Hi @magnusrodseth, you can remove the button from our components via the [Appearance prop](https://clerk.dev/docs/component-customization/appearance-prop).

In Q2 2023, we will add the capability to disable organization creation based on the user role on the API level.

**Comment by magnusrodseth** [comment]
Lovely! I'll leave a code snippet if someone else has the same case as me down the line:

```tsx
<OrganizationSwitcher
              appearance={{
                elements: {
                  organizationSwitcherPopoverActionButton__createOrganization: {
                    display: "none",
                  },
                },
              }}
            />
```

**Comment by SokratisVidros** [comment]
Thanks @magnusrodseth
