### ISSUE TITLE
serve all clerk hosted images with `crossorigin="anonymous"` attribute so that they can be viewed with COEP.

### ISSUE THREAD

**Issue by nicksrandall** [clerkinc/javascript#919]
## Package + Version

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
4.8.0
```

### Browser/OS

Chrome latest

## Description

There is a feature of the site that I'm working on that requires that I serve my content ["Cross-Origin Isolated"](https://web.dev/coop-coep/). This requires that all assets from 3rd party domains (clerk) specifically opt into allowing cross-origin requests by adding the `crossorigin=" anonymous"` attribute. This applies to images, videos, and scripts.

The specific issue I've run into is that the social button icons do not show up.

**Comment by SokratisVidros** [comment]
Thanks for reporting. We will fix it this week.

**Comment by nicksrandall** [comment]
Any progress on this? All Clerk images are not now showing up in my app. 

Note that the images themselves need also to be served with CORs headers. Images from the `images.clerk.dev` domain appear not to have appropriate cors headers.

**Comment by nicksrandall** [comment]
Working
