### ISSUE TITLE
Cannot find module '#crypto' from 'node_modules/@clerk/backend/dist/index.js'

### ISSUE THREAD

**Issue by rleshchenko** [clerkinc/javascript#920]
## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [x] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
4.7.9
```

### Browser/OS

Any linux system

## Description

I have this error when trying to use clerk on my node 19 backend:
Cannot find module '#crypto' from 'node_modules/@clerk/backend/dist/index.js'
Here is a version of clerk package:
"@clerk/clerk-sdk-node": "^4.7.9",

**Comment by nikosdouvlis** [comment]
Hello there, thanks for the report. 

I'll investigate and get back to you with more details soon.

**Comment by rleshchenko** [comment]
@nikosdouvlis , i've created a repo with a bug:
https://github.com/rleshchenko/clerkbug/actions/runs/4402376370/jobs/7709471709

**Comment by nathanielescribano** [comment]
Running into this same issue as well.

**Comment by christianmat** [comment]
Same issue. Any updates @nikosdouvlis ?

**Comment by perkinsjr** [comment]
Adding 

moduleNameMapper: {
    '#crypto': '@clerk/backend/dist/runtime/node/crypto.js',
    '#fetch': '@clerk/backend/dist/runtime/node/fetch.js',
  },

to your jest config will resolve this error.

**Comment by nathanielescribano** [comment]
@perkinsjr to the rescue!! Seems to be working now - thanks a ton!

**Comment by nikosdouvlis** [comment]
Closing this one as what @perkinsjr posted is the correct workaround for now :) 
You can refer to https://github.com/facebook/jest/issues/12270 for more info.
