### ISSUE TITLE
Unexpected Type Error from react/nextjs lib when trying to delete user's default email

### ISSUE THREAD

**Issue by AllanOliveiraM** [clerkinc/javascript#932]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [x] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
4.11.7
```

### Browser/OS

Running on Chrome latest or Firefox with Ubuntu 22.04

## Description

I usually try everything possible before proceeding, so I decided to test the functionality of the embeddable components. When trying to delete a user's default email, (I know it's a rather unusual action) I get an error that I believe is internal to the lib.

Apparently we have a value not reaching where it should.

I'm testing through the development environment, and the component I'm referring to is UserProfile.

I'm using I18N, so the UI is in Portuguese. I used only the prop appearance of this component, and I'm passing the translation object through the prodider.

I'm sure the environment variables are ok, and the other library features work normally.

I couldn't find this in the documentation, changelog, or issues here on github 😢 

Interestingly, the error persists when refreshing the page (you no longer need to try to delete the email, the exception simply occurs when trying to render the component).

The only way to stop the error is to log out via the user button, or without sharing/clearing cookies/local storage...

This only happens with the default email, not others.

Apparently to reproduce just try to delete the default email anyway, in any environment
If necessary, I put it in CodeSandbox

If I understood a little more about the lib I would dig through the source code, but I'm not there yet

![image](https://user-images.githubusercontent.com/41436010/225199705-1e8b9cb4-3e56-46e6-98c5-e276594a3453.png)

![image](https://user-images.githubusercontent.com/41436010/225200175-1400b04d-ab9f-4d16-a919-5227d04a8500.png)

**Comment by nikosdouvlis** [comment]
Hello @AllanOliveiraM - this has been resolved, and the fix will be deployed with our next release tomorrow.
Many thanks for the report :)
