### ISSUE TITLE
`OrganizationProfile` with path routing has incorrect link

### ISSUE THREAD

**Issue by Ehesp** [clerkinc/javascript#938]
- [ ] Review the documentation: https://docs.clerk.dev/
- [ ] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [ ] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [x] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [x] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
2.2.11
```

## Description

When using path based routing with the `OrganizationProfile` component, it's possible to break the navigation - note this is using v2 Remix routing in the `routes/settings.$/route.tsx` directory/file.

```tsx
<OrganizationProfile
    routing="path"
    path="/settings"
    afterLeaveOrganizationUrl="/"
/>
```

The page is rendered correctly:

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/842078/225431626-f26e7529-b9a4-409c-8a12-d7f0545b82ab.png">

Clicking on "Settings" works, and changes the URL (`/settings/organization-settings`). Then clicking on my Org settings takes me to the profile route (`/settings/organization-settings/profile`):

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/842078/225431987-e979eac4-7e49-4e2d-b1e6-40dd5e578b72.png">

However, if I then click "Cancel", or finish the update flow, the URL updates to `/settings/settings/organization-settings`, which isn't valid.

**Comment by desiprisg** [comment]
We've pushed a fix for this. Thanks!
