### ISSUE TITLE
Invalid Auth token causes the node process to crash

### ISSUE THREAD

**Issue by AllanOliveiraM** [clerkinc/javascript#953]
- [x] Review the documentation: https://docs.clerk.dev/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [x] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Version:

```
^4.7.13
```

### Browser/OS

x

## Description

When performing a request with Authorization header with a token value that is invalid, in this case I inserted an "s" character before the complete token string, an error causes the node process to crash

![image](https://user-images.githubusercontent.com/41436010/226228869-f14fec1a-39ad-4ccf-8e5c-926b8fcc148c.png)

I using Nest ClerkExpressRequireAuth Middlware

I believe a try catch is needed here:

![image](https://user-images.githubusercontent.com/41436010/226229256-4ba05948-569b-4668-97f4-41a9c2dfa8f9.png)
![image](https://user-images.githubusercontent.com/41436010/226229116-ea81b411-871b-4edb-b1d2-01ee05c1ab6d.png)

This error causes a crash that I couldn't handle with ExceptionFilters
Any suggestion?
i think this can be used for dos

**Comment by dimkl** [comment]
Fixed in `@clerk/clerk-sdk-node@4.7.15` release. Thank you for reporting it!
