### ISSUE TITLE
Sign-out issue 

### ISSUE THREAD

**Issue by tasos77** [clerkinc/javascript#954]
Hello there , I'm using  @clerk/clerk-js : ^4.27.2 in my nuxt3 project and i have an issue when i try to use signOut function. 
So when i want to logout a user from my app , I try to run  await window.Clerk.signOut(); then redirect to login page but every time after that my console fills with a certain error :

Uncaught (in promise) Error: ClerkJS: Token refresh failed (error='[Error]
Message:
Status:401
Serialized errors: {"code":"signed_out","message":"Signed out","longMessage":"You are signed out","meta":{}}')

Am I missing something?

**Comment by dimkl** [comment]
Hello @tasos77 . Thank you for using Clerk and for reporting this issue.
Could you provide a github template or repository to reproduce and investigate the issue ?

**Comment by tasos77** [comment]
Sr for the waiting, i solve the issue by globalize

**Comment by tasos77** [comment]
Sr for the waiting, i solved the issue by globalize the clerk obj using nuxt3 plugin provide attr
