### ISSUE TITLE
rootAuthLoader breaks TypeScript types for a loader in Remix

### ISSUE THREAD

**Issue by tmcw** [clerkinc/javascript#972]
- [x] Review the documentation: https://docs.clerk.com/
- [x] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [x] Go through package changelog files.
- [x] Provide the Frontend API key from your application dashboard.

## Package + Version

- [x] `@clerk/remix`: 2.2.17

### Dependencies + versions

Provide a json with the dependencies used in your project (copy paste from yarn.lock / package-lock.json) or a github project / template that reproduces the issue.

**Please remember to include the `@clerk/*` packages and their versions!!**

Example:

```json
{  
  "dependencies": {
    "react": "18.2.0",
    "@remix-run/node": "^1.14.3",
    "@remix-run/react": "^1.14.3",
    "@remix-run/serve": "^1.14.3",
    "@clerk/remix": "^2.2.17"
  }
}

```

## Description

Example:

```ts
import { rootAuthLoader } from "@clerk/remix/ssr.server";
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";

export const loader1 = () => {
  return json({
    x: 10,
  });
};

export const loader2 = (args) =>
  rootAuthLoader(
    args,
    ({ request }) => {
      return json({
        auth: request.auth,
        x: 10,
      });
    },
    { loadUser: true }
  );

const data1 = useLoaderData<typeof loader1>();
const data2 = useLoaderData<typeof loader2>();
```

- `data1` is typed `SerializeObject<UndefinedToOptional<{x: number}>>`
- `data2` is typed `any`

The `rootAuthLoader` method appears to throw away any inferred types from the loader passed to it:

https://github.com/clerkinc/javascript/blob/0b0c7d719abb06632f5e13c3d09ab666a1fb21b3/packages/remix/src/ssr/types.ts#L25-L33

Instead, it should merge or return the inferred type.

**Comment by dimkl** [comment]
Hello @tmcw 👋 .Thank you for reporting this issue.
I will take a look at this and come back to you. Until then if you think you have found the root cause, you can always open a PR and i would be happy to review it.

**Comment by dimkl** [comment]
@tmcw you can find the fix in the latest release.
