### ISSUE TITLE
Provide webhook types

### ISSUE THREAD

**Issue by tmcw** [clerkinc/javascript#982]
## Package

- [x] `@clerk/types`

## Description

As far as I can tell, Clerk does not provide TypeScript types for Webhook contents. There's a generic/naive implementation [in the Next.js example](https://github.com/clerkinc/clerk-nextjs-examples/blob/main/examples/widget/pages/api/webhooks/user.ts#L49). It would be nice to have something more concrete, and more clear documentation on this point - a type that included all of the possible variations and their contents. The [documentation for webhooks](https://clerk.com/docs/integration/webhooks#payload-structure) is fine but not complete or explicit.

**Comment by dimkl** [comment]
@tmcw Thank you for reporting it. :) 
I will open an internal ticket to add it in our next planning.

**Comment by tmcw** [comment]
This is tricky in part because, from first glance, something like this would work:

```ts
import {
  User,
  Session,
  Organization,
  OrganizationMembership,
  OrganizationInvitation,
} from "@clerk/backend";

/**
 * https://clerk.com/docs/integration/webhooks#payload-structure
 */
export type WebhookEvent =
  | {
      type: "user.created" | "user.deleted" | "user.updated";
      object: "event";
      data: User;
    }
```

But the types exported by clerk/backend include camelcased properties like emailAddresses, whereas the API returns underscore-formatted properties like `email_addresses`

**Comment by tmcw** [comment]
Yep, that works great, thanks for the tip!

**Comment by tmcw** [comment]
This was merged, which is great, but afaict, the [types aren't exported](https://unpkg.com/browse/@clerk/backend@0.17.0/dist/types/api/resources/index.d.ts) from Clerk's module, so they aren't yet usable.

**Comment by dimkl** [comment]
@tmcw sorry for the inconvenience: https://github.com/clerkinc/javascript/pull/1076
I will ping you when it's released.

**Comment by desiprisg** [comment]
The types should be available using the latest versions.
