### ISSUE TITLE
Invalid URL created when using Next.js 13 app directory (http://localhost:3000/sign-inredirect_url=http:/localhost:3000/protected)

### ISSUE THREAD

**Issue by r3Fuze** [clerkinc/javascript#997]
- [X] Review the documentation: https://docs.clerk.com/
- [X] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [X] Go through package changelog files.
- [X] Provide the Frontend API key from your application dashboard. (pk_test_cHJvdWQtZGFuZS04Ni5jbGVyay5hY2NvdW50cy5kZXYk)

## Package + Version

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [X] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`
- [ ] other:

### Dependencies + versions

**Pages directory repo that works**: https://github.com/r3Fuze/next-pages-dir-clerk-redirect
**App directory repo that doesn't work**: https://github.com/r3Fuze/next-app-dir-clerk-redirect

Dependencies for non-functional app directory version.

```json
"dependencies": {
  "@clerk/nextjs": "^4.11.14",
  "@types/node": "18.15.11",
  "@types/react": "18.0.31",
  "@types/react-dom": "18.0.11",
  "autoprefixer": "10.4.14",
  "eslint": "8.37.0",
  "eslint-config-next": "13.2.4",
  "next": "13.2.4",
  "postcss": "8.4.21",
  "react": "18.2.0",
  "react-dom": "18.2.0",
  "tailwindcss": "3.3.0",
  "typescript": "5.0.2"
}
```

### Browser/OS

Firefox  112, Node 19.7.0, Windows 10

## Description

Clerk will create an invalid URL when used with the Next.js 13 app directory. A (mostly) identical version using the pages directory works fine.

Both versions were created by following the steps in the beta docs ([pages](https://beta-docs.clerk.com/quickstarts/nextjs/stable), [app](https://beta-docs.clerk.com/quickstarts/nextjs/app-router))

See the `Dependencies + versions` section for repos for both versions.

#### Reproduction steps for the app directory version
- Be signed out on the home page
- Navigate to `/protected`
- Redirected to `http://localhost:3000/sign-in?redirect_url=http%3A%2F%2Flocalhost%3A3000%2Fprotected`
- Sign in with GitHub or email (I've only tried those two, but they both fail)
- Redirected to `http://localhost:3000/sign-inredirect_url=http:/localhost:3000/protected`

Notice the missing `?` between `sign-in` and `redirect_url`. There is also a missing `/` in the protocol for the `redirect_url`

The same steps in the pages directory version create a valid URL at the end and redirect to `/protected` without problems.

Related support thread from the Discord: https://discord.com/channels/856971667393609759/1070730863077236846

Let me know if you need any more information.

**Comment by panteliselef** [comment]
Hey @r3Fuze, thank you for report this issue. I confirm that this seems to be reproducible. 
Until the issue is resolved and as a temporary workaround you could use the following

```tsx
import { SignIn } from "@clerk/nextjs/app-beta"

export default function Page({
  params,
  searchParams,
}: {
  params: { slug: string };
  searchParams: { [key: string]: string | undefined };
}) {
  return <SignIn path="/sign-in" signUpUrl="/sign-up" redirectUrl={searchParams.redirect_url || '/'} />
}
```
